@startuml

class Pokemon {
+ main(String[] args: String[])
}

class Jeu {
- scanner : Scanner
- joueur1 : Dresseur
- joueur2 : Dresseur
- joueurActuel : Dresseur
- numeroTour : int
- nomsPokemon : String[*]
- joueurAdverse : JoueurOrdinateur
+ «create» Jeu (joueur1 : Dresseur, joueur2 : Dresseur)
+ jouerTour()
+ trouverCarteDansTerrainJoueurAdverse(nomCarte : String, joueurActuel : Dresseur) : CartePokemon
+ afficherCartesTerrainJoueur2() : String
+ trouverCarteDansTerrainJoueur2(nomCarte : String) : CartePokemon
+ prochainTour()
+ afficherMainJoueur2() : String
+ afficherCarteMainJoueur2() : String
+ trouverCarteDansMainJoueur2(nomCarte : String) : CartePokemon
+ genererPokemon() : CartePokemon
+ getJoueurAdverse(joueurActuel : Dresseur) : Dresseur
}


class Dresseur {
# nom : String
# main : String[*]
# pioche : String[*]
# defausse : String[*]
# terrain : String[*]
- vieRestante : int
+ «create» Dresseur(nom : String)
+ getTerrain() : String[*]
+ piocher()
+ afficherPioche()
+ afficherDefausse()
+ afficherMain()
+ getNom() : String
+ getMain() : String[*]
+ getPioche() : String[*]
+ jouerCarte(carte : CartePokemon)
+ ajouterCarteAPioche(carte : CartePokemon)
+ ajouterCarte(carte : CartePokemon)
+ placerPokemonSurTerrain(carte : CartePokemon) : boolean
+ defausserPokemon(pokemon : CartePokemon)
+ afficherCartesTerrainAvecIndex() : String
+ getVieRestante() : Integer
+ setVieRestante(vieRestante : Integer)

}

class CartePokemon {
- nom : String
- affinite : Type
- vie : int
- vieMax : int
- attaque : int
+ CartePokemon(nom : String, affinite : Type, vie : int, vieMax : int, attaque : int)
+ getNom() : String
+ getVie() : int
+ getVieMax() : int
+ getAttaque() : int
+ getAffinite() : Type
+ attaquer(pokemonCible : CartePokemon)
+ afficherCarte()
}

class JoueurOrdinateur extends Dresseur {
- nom : String
- main : String[*]
- pioche : String[*]
- defausse : String[*]
- terrain : String[*]
+ JoueurOrdinateur(nom : String)
+ jouerTour(jeu : Jeu)
+ trouverPokemonACibler(adversaire : Dresseur) : CartePokemon
}



abstract class Type {
#-m_type : String
+ Type (type : Type)
+ getType() : Type
+ abstract getAvantage() : Type
+ abstract getType() : Type
}

class Air {
+ «create» Air()
+ getAvantage() : Type
+ getType(): Type
}

class Eau {
+ «create» Eau()
+ getAvantage() : Type
+ getType(): Type
}

class Feu {
+ «create» Feu()
+ getAvantage() : Type
+ getType(): Type
}

class Terre {
+ «create» Terre()
+ getAvantage() : Type
+ getType(): Type
}

abstract class Pouvoir {
+ Pouvoir ()
}

class SoinTotal {
- m_utilisation: Integer
+ «create» SoinTotal()
+ soignerTotalement(carte : CartePokemon)
+ getUtilisation() : Integer
+ setUtilisation(utilisation : Integer)
+ toString(): String
}

class SoinSimple {
- m_soin;
- m_utilisation: Integer
+ «create» SoinSimple()
+ soigner(carte : CartePokemon)
+ getSoin() : Integer
+ getUtilisation() : Integer
+ setUtilisation(utilisation : Integer)
+ toString(): String
}

class Kamikaze {
- m_utilisation: Integer
+ «create» Kamikaze()
+ exploser(carte : CartePokemon)
+ getUtilisation() : Integer
+ setUtilisation(utilisation : Integer)
+ toString(): String
}

Air --|> Type
Terre --|> Type
Eau --|> Type
Feu --|> Type
SoinSimple --|> Pouvoir
SoinTotal --|> Pouvoir
Kamikaze --|> Pouvoir
CartePokemon "1" *-- "1" Pouvoir
CartePokemon "1" *-- "1" Type : affinite
Dresseur "1" *-- "0..*" CartePokemon : possède
Pokemon --> JoueurOrdinateur
Pokemon --> Dresseur
Pokemon --> Jeu
JoueurOrdinateur --> Jeu : utilise
JoueurOrdinateur o--> CartePokemon
JoueurOrdinateur --> Dresseur : hérite
Jeu --> CartePokemon
@enduml
